// <auto-generated />
using System;
using Curvia.Persistence.EntityFrameworkCore.PersistenceContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curvia.Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CurviaDbContext))]
    partial class CurviaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Curvia.Domain.Features.Routing.RoutePlans.Aggregate.RoutePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RoutePlans", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.Routes.Aggregate.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geometry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoutePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.RoutePlans.Aggregate.RoutePlan", b =>
                {
                    b.OwnsOne("Templates.Core.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "End", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("EndLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("EndLongitude");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "Start", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("StartLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("StartLongitude");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.LoopSpec", "LoopSpec", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsLoop")
                                .HasColumnType("bit")
                                .HasColumnName("IsLoop");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "TargetDistance", b2 =>
                                {
                                    b2.Property<Guid>("LoopSpecRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("LoopTargetDistanceMeters");

                                    b2.HasKey("LoopSpecRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("LoopSpecRoutePlanId");
                                });

                            b1.Navigation("TargetDistance")
                                .IsRequired();
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.RoutingConstraints", "Constraints", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AvoidHighways")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidHighways");

                            b1.Property<bool>("AvoidTolls")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidTolls");

                            b1.Property<double>("MaxDetourRatio")
                                .HasColumnType("float")
                                .HasColumnName("MaxDetourRatio");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "MaxDistance", b2 =>
                                {
                                    b2.Property<Guid>("RoutingConstraintsRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("MaxDistanceMeters");

                                    b2.HasKey("RoutingConstraintsRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("RoutingConstraintsRoutePlanId");
                                });

                            b1.Navigation("MaxDistance");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.ScoringProfile", "ScoringProfile", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("FunFactor")
                                .HasColumnType("float")
                                .HasColumnName("FunFactor");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.ScoringWeights", "Weights", b2 =>
                                {
                                    b2.Property<Guid>("ScoringProfileRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Curves")
                                        .HasColumnType("float")
                                        .HasColumnName("WeightCurves");

                                    b2.Property<double>("Elevation")
                                        .HasColumnType("float")
                                        .HasColumnName("WeightElevation");

                                    b2.Property<double>("Scenery")
                                        .HasColumnType("float")
                                        .HasColumnName("WeightScenery");

                                    b2.HasKey("ScoringProfileRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("ScoringProfileRoutePlanId");
                                });

                            b1.Navigation("Weights")
                                .IsRequired();
                        });

                    b.OwnsMany("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Waypoint", "Waypoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RoutePlanId");

                            b1.ToTable("RoutePlanWaypoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "Location", b2 =>
                                {
                                    b2.Property<Guid>("WaypointId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("WaypointId");

                                    b2.ToTable("RoutePlanWaypoints");

                                    b2.WithOwner()
                                        .HasForeignKey("WaypointId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Constraints")
                        .IsRequired();

                    b.Navigation("End");

                    b.Navigation("LoopSpec");

                    b.Navigation("ScoringProfile")
                        .IsRequired();

                    b.Navigation("Start")
                        .IsRequired();

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.Routes.Aggregate.Route", b =>
                {
                    b.OwnsOne("Templates.Core.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.RouteStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "Distance", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("DistanceMeters");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.ElevationGain", "ElevationGain", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("ElevationGainMeters");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.Duration", "EstimatedDuration", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<long>("Seconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("DurationSeconds");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.FunScore", "FunScore", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("FunScore");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.Navigation("Distance")
                                .IsRequired();

                            b1.Navigation("ElevationGain");

                            b1.Navigation("EstimatedDuration");

                            b1.Navigation("FunScore");
                        });

                    b.OwnsMany("Curvia.Domain.Features.Routing.Routes.Entities.RouteSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Geometry")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RouteId");

                            b1.ToTable("RouteSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("Templates.Core.Domain.Primitives.AuditInfo", "Audit", b2 =>
                                {
                                    b2.Property<Guid>("RouteSegmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("CreatedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("ModifiedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime?>("ModifiedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("RouteSegmentId");

                                    b2.ToTable("RouteSegments");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteSegmentId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.RouteStats", "Stats", b2 =>
                                {
                                    b2.Property<Guid>("RouteSegmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("RouteSegmentId");

                                    b2.ToTable("RouteSegments");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteSegmentId");

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "Distance", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Meters")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentDistanceMeters");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.ElevationGain", "ElevationGain", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Meters")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentElevationGainMeters");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.Duration", "EstimatedDuration", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<long>("Seconds")
                                                .HasColumnType("bigint")
                                                .HasColumnName("SegmentDurationSeconds");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.FunScore", "FunScore", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Value")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentFunScore");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.Navigation("Distance")
                                        .IsRequired();

                                    b2.Navigation("ElevationGain");

                                    b2.Navigation("EstimatedDuration");

                                    b2.Navigation("FunScore");
                                });

                            b1.Navigation("Audit")
                                .IsRequired();

                            b1.Navigation("Stats")
                                .IsRequired();
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("MaxLatitude")
                                .HasColumnType("float")
                                .HasColumnName("MaxLatitude");

                            b1.Property<double>("MaxLongitude")
                                .HasColumnType("float")
                                .HasColumnName("MaxLongitude");

                            b1.Property<double>("MinLatitude")
                                .HasColumnType("float")
                                .HasColumnName("MinLatitude");

                            b1.Property<double>("MinLongitude")
                                .HasColumnType("float")
                                .HasColumnName("MinLongitude");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("BoundingBox")
                        .IsRequired();

                    b.Navigation("Segments");

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
