// <auto-generated />
using System;
using Curvia.Persistence.EntityFrameworkCore.PersistenceContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curvia.Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CurviaDbContext))]
    partial class CurviaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.Hazard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalId");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("HazardType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSyncedUtc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Source");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Source")
                        .HasDatabaseName("IX_Hazards_CountryCode_Source");

                    b.HasIndex("ExternalId", "Source", "CountryCode")
                        .HasDatabaseName("IX_Hazards_ExternalId_Source_CountryCode");

                    b.ToTable("Hazards", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalId");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("IncidentType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSyncedUtc");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Source");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFromUtc");

                    b.Property<DateTime>("ValidUntilUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidUntilUtc");

                    b.HasKey("Id");

                    b.HasIndex("ValidUntilUtc")
                        .HasDatabaseName("IX_Incidents_ValidUntilUtc");

                    b.HasIndex("CountryCode", "Source")
                        .HasDatabaseName("IX_Incidents_CountryCode_Source");

                    b.HasIndex("ExternalId", "Source", "CountryCode")
                        .HasDatabaseName("IX_Incidents_ExternalId_Source_CountryCode");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.RoadWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSyncedUtc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFromUtc");

                    b.Property<DateTime>("ValidUntilUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidUntilUtc");

                    b.HasKey("Id");

                    b.HasIndex("ValidUntilUtc")
                        .HasDatabaseName("IX_RoadWorks_ValidUntilUtc");

                    b.HasIndex("CountryCode", "Source")
                        .HasDatabaseName("IX_RoadWorks_CountryCode_Source");

                    b.HasIndex("ExternalId", "Source", "CountryCode")
                        .HasDatabaseName("IX_RoadWorks_ExternalId_Source_CountryCode");

                    b.ToTable("RoadWorks", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.SpeedCamera", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Direction");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSyncedUtc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Source");

                    b.Property<int?>("SpeedLimit")
                        .HasColumnType("int")
                        .HasColumnName("SpeedLimitKmh");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Source")
                        .HasDatabaseName("IX_SpeedCameras_CountryCode_Source");

                    b.HasIndex("ExternalId", "Source", "CountryCode")
                        .HasDatabaseName("IX_SpeedCameras_ExternalId_Source_CountryCode");

                    b.ToTable("SpeedCameras", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.MotorcycleCatalog.Aggregates.MotorcycleCatalogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MakerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MakerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("SuggestedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SuggestedByUserId");

                    b.HasKey("Id");

                    b.HasIndex("MakerId")
                        .HasDatabaseName("IX_MotorcycleModels_MakerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MotorcycleModels_Status");

                    b.ToTable("MotorcycleModels", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.MotorcycleCatalog.Aggregates.MotorcycleMaker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("SuggestedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SuggestedByUserId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_MotorcycleMakers_Name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MotorcycleMakers_Status");

                    b.ToTable("MotorcycleMakers", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Motorcycles.Aggregates.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int?>("EngineCc")
                        .HasColumnType("int")
                        .HasColumnName("EngineCc");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDefault");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Maker");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Model");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nickname");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Motorcycles_UserId");

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.RoutePlans.Aggregate.RoutePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RoutePlans", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.Routes.Aggregate.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geometry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoutePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.SavedRoutes.Aggregate.SavedRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RouteId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("Visibility");

                    b.HasKey("Id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("IX_SavedRoutes_RouteId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SavedRoutes_UserId");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("IX_SavedRoutes_Visibility");

                    b.ToTable("SavedRoutes", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Users.Aggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("KeycloakId");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Locale");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_Email");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_KeycloakId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.Hazard", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("HazardId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOnUtc");

                            b1.HasKey("HazardId");

                            b1.ToTable("Hazards");

                            b1.WithOwner()
                                .HasForeignKey("HazardId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Awareness.ValueObjects.Coordinate", "Position", b1 =>
                        {
                            b1.Property<Guid>("HazardId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("HazardId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_Hazards_Latitude_Longitude");

                            b1.ToTable("Hazards");

                            b1.WithOwner()
                                .HasForeignKey("HazardId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.Incident", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOnUtc");

                            b1.HasKey("IncidentId");

                            b1.ToTable("Incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Awareness.ValueObjects.Coordinate", "Position", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("IncidentId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_Incidents_Latitude_Longitude");

                            b1.ToTable("Incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.RoadWork", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RoadWorkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOnUtc");

                            b1.HasKey("RoadWorkId");

                            b1.ToTable("RoadWorks");

                            b1.WithOwner()
                                .HasForeignKey("RoadWorkId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Awareness.ValueObjects.Coordinate", "Position", b1 =>
                        {
                            b1.Property<Guid>("RoadWorkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("RoadWorkId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_RoadWorks_Latitude_Longitude");

                            b1.ToTable("RoadWorks");

                            b1.WithOwner()
                                .HasForeignKey("RoadWorkId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.Awareness.Aggregates.SpeedCamera", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("SpeedCameraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOnUtc");

                            b1.HasKey("SpeedCameraId");

                            b1.ToTable("SpeedCameras");

                            b1.WithOwner()
                                .HasForeignKey("SpeedCameraId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Awareness.ValueObjects.Coordinate", "Position", b1 =>
                        {
                            b1.Property<Guid>("SpeedCameraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("SpeedCameraId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_SpeedCameras_Latitude_Longitude");

                            b1.ToTable("SpeedCameras");

                            b1.WithOwner()
                                .HasForeignKey("SpeedCameraId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.MotorcycleCatalog.Aggregates.MotorcycleCatalogModel", b =>
                {
                    b.HasOne("Curvia.Domain.Features.MotorcycleCatalog.Aggregates.MotorcycleMaker", null)
                        .WithMany()
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MotorcycleModels_MotorcycleMakers_MakerId");

                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MotorcycleCatalogModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("MotorcycleCatalogModelId");

                            b1.ToTable("MotorcycleModels");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleCatalogModelId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.MotorcycleCatalog.Aggregates.MotorcycleMaker", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MotorcycleMakerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("MotorcycleMakerId");

                            b1.ToTable("MotorcycleMakers");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleMakerId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.Motorcycles.Aggregates.Motorcycle", b =>
                {
                    b.HasOne("Curvia.Domain.Features.Users.Aggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Motorcycles_AppUsers_UserId");

                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MotorcycleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOnUtc");

                            b1.HasKey("MotorcycleId");

                            b1.ToTable("Motorcycles");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.RoutePlans.Aggregate.RoutePlan", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "End", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("EndLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("EndLongitude");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "Start", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("StartLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("StartLongitude");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.LoopSpec", "LoopSpec", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsLoop")
                                .HasColumnType("bit")
                                .HasColumnName("IsLoop");

                            b1.Property<int>("ReturnStrategy")
                                .HasColumnType("int")
                                .HasColumnName("LoopReturnStrategy");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "TargetDistance", b2 =>
                                {
                                    b2.Property<Guid>("LoopSpecRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("LoopTargetDistanceMeters");

                                    b2.HasKey("LoopSpecRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("LoopSpecRoutePlanId");
                                });

                            b1.Navigation("TargetDistance")
                                .IsRequired();
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.RoutingConstraints", "Constraints", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AvoidFerries")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidFerries");

                            b1.Property<bool>("AvoidHighways")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidHighways");

                            b1.Property<bool>("AvoidMotorwayLinks")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidMotorwayLinks");

                            b1.Property<bool>("AvoidTolls")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidTolls");

                            b1.Property<bool>("AvoidUnpaved")
                                .HasColumnType("bit")
                                .HasColumnName("AvoidUnpaved");

                            b1.Property<double>("MaxDetourRatio")
                                .HasColumnType("FLOAT")
                                .HasColumnName("MaxDetourRatio");

                            b1.Property<long?>("MaxDurationSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxDurationSeconds");

                            b1.Property<int>("UrbanTolerance")
                                .HasColumnType("int")
                                .HasColumnName("UrbanTolerance");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "MaxDistance", b2 =>
                                {
                                    b2.Property<Guid>("RoutingConstraintsRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("MaxDistanceMeters");

                                    b2.HasKey("RoutingConstraintsRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("RoutingConstraintsRoutePlanId");
                                });

                            b1.Navigation("MaxDistance");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.ScoringProfile", "ScoringProfile", b1 =>
                        {
                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("FunFactor")
                                .HasColumnType("FLOAT")
                                .HasColumnName("FunFactor");

                            b1.HasKey("RoutePlanId");

                            b1.ToTable("RoutePlans");

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.ScoringWeights", "Weights", b2 =>
                                {
                                    b2.Property<Guid>("ScoringProfileRoutePlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("CurvesWeight")
                                        .HasColumnType("FLOAT")
                                        .HasColumnName("WeightCurves");

                                    b2.Property<double>("ElevationWeight")
                                        .HasColumnType("FLOAT")
                                        .HasColumnName("WeightElevation");

                                    b2.Property<double>("SceneryWeight")
                                        .HasColumnType("FLOAT")
                                        .HasColumnName("WeightScenery");

                                    b2.HasKey("ScoringProfileRoutePlanId");

                                    b2.ToTable("RoutePlans");

                                    b2.WithOwner()
                                        .HasForeignKey("ScoringProfileRoutePlanId");
                                });

                            b1.Navigation("Weights")
                                .IsRequired();
                        });

                    b.OwnsMany("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Waypoint", "Waypoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RoutePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RoutePlanId");

                            b1.ToTable("RoutePlanWaypoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoutePlanId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.GeoCoordinate", "Location", b2 =>
                                {
                                    b2.Property<Guid>("WaypointId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("WaypointId");

                                    b2.ToTable("RoutePlanWaypoints");

                                    b2.WithOwner()
                                        .HasForeignKey("WaypointId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Constraints")
                        .IsRequired();

                    b.Navigation("End");

                    b.Navigation("LoopSpec");

                    b.Navigation("ScoringProfile")
                        .IsRequired();

                    b.Navigation("Start")
                        .IsRequired();

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("Curvia.Domain.Features.Routing.Routes.Aggregate.Route", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.RouteStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "Distance", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("DistanceMeters");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.ElevationGain", "ElevationGain", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("ElevationGainMeters");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.Duration", "EstimatedDuration", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<long>("Seconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("DurationSeconds");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.FunScore", "FunScore", b2 =>
                                {
                                    b2.Property<Guid>("RouteStatsRouteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("FunScore");

                                    b2.HasKey("RouteStatsRouteId");

                                    b2.ToTable("Routes");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteStatsRouteId");
                                });

                            b1.Navigation("Distance")
                                .IsRequired();

                            b1.Navigation("ElevationGain");

                            b1.Navigation("EstimatedDuration");

                            b1.Navigation("FunScore");
                        });

                    b.OwnsMany("Curvia.Domain.Features.Routing.Routes.Entities.RouteSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Geometry")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RouteId");

                            b1.ToTable("RouteSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b2 =>
                                {
                                    b2.Property<Guid>("RouteSegmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("CreatedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("ModifiedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime?>("ModifiedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("RouteSegmentId");

                                    b2.ToTable("RouteSegments");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteSegmentId");
                                });

                            b1.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.RouteStats", "Stats", b2 =>
                                {
                                    b2.Property<Guid>("RouteSegmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("RouteSegmentId");

                                    b2.ToTable("RouteSegments");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteSegmentId");

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.RoutePlans.ValueObjects.Distance", "Distance", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Meters")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentDistanceMeters");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.ElevationGain", "ElevationGain", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Meters")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentElevationGainMeters");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.Duration", "EstimatedDuration", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<long>("Seconds")
                                                .HasColumnType("bigint")
                                                .HasColumnName("SegmentDurationSeconds");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.OwnsOne("Curvia.Domain.Features.Routing.Routes.ValueObjects.FunScore", "FunScore", b3 =>
                                        {
                                            b3.Property<Guid>("RouteStatsRouteSegmentId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<double>("Value")
                                                .HasColumnType("float")
                                                .HasColumnName("SegmentFunScore");

                                            b3.HasKey("RouteStatsRouteSegmentId");

                                            b3.ToTable("RouteSegments");

                                            b3.WithOwner()
                                                .HasForeignKey("RouteStatsRouteSegmentId");
                                        });

                                    b2.Navigation("Distance")
                                        .IsRequired();

                                    b2.Navigation("ElevationGain");

                                    b2.Navigation("EstimatedDuration");

                                    b2.Navigation("FunScore");
                                });

                            b1.Navigation("Audit")
                                .IsRequired();

                            b1.Navigation("Stats")
                                .IsRequired();
                        });

                    b.OwnsOne("Curvia.Domain.Shared.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("East")
                                .HasColumnType("float")
                                .HasColumnName("BBoxEast");

                            b1.Property<double>("North")
                                .HasColumnType("float")
                                .HasColumnName("BBoxNorth");

                            b1.Property<double>("South")
                                .HasColumnType("float")
                                .HasColumnName("BBoxSouth");

                            b1.Property<double>("West")
                                .HasColumnType("float")
                                .HasColumnName("BBoxWest");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("BoundingBox")
                        .IsRequired();

                    b.Navigation("Segments");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("Curvia.Domain.Features.SavedRoutes.Aggregate.SavedRoute", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("SavedRouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("SavedRouteId");

                            b1.ToTable("SavedRoutes");

                            b1.WithOwner()
                                .HasForeignKey("SavedRouteId");
                        });

                    b.OwnsMany("Curvia.Domain.Features.SavedRoutes.Entities.RouteReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<string>("Comment")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("Comment");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("DeletedBy");

                            b1.Property<DateTime?>("DeletedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedOnUtc");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("IsDeleted");

                            b1.Property<int>("Rating")
                                .HasColumnType("int")
                                .HasColumnName("Rating");

                            b1.Property<DateTime>("ReviewedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("ReviewerUserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ReviewerUserId");

                            b1.Property<Guid>("SavedRouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SavedRouteId", "ReviewerUserId")
                                .IsUnique()
                                .HasDatabaseName("UX_RouteReviews_SavedRouteId_ReviewerUserId");

                            b1.ToTable("RouteReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SavedRouteId");

                            b1.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b2 =>
                                {
                                    b2.Property<Guid>("RouteReviewId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("CreatedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("ModifiedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime?>("ModifiedOnUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("RouteReviewId");

                                    b2.ToTable("RouteReviews");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteReviewId");
                                });

                            b1.Navigation("Audit")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Curvia.Domain.Features.Users.Aggregate.User", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
