<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Templates.Core.Containers.API" Version="8.4.0" />
    <PackageReference Include="Templates.Core.Tools.DependencyInjection" Version="8.4.0" />
  </ItemGroup>

</Project>
