//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curvia.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curvia.Domain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoundingBox is invalid. Ensure min/max lat/lon are within valid ranges..
        /// </summary>
        internal static string Routing_BoundingBox_Invalid {
            get {
                return ResourceManager.GetString("Routing_BoundingBox_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoundingBox is inverted. {0}.
        /// </summary>
        internal static string Routing_BoundingBox_Inverted {
            get {
                return ResourceManager.GetString("Routing_BoundingBox_Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoundingBox must have a nonzero area..
        /// </summary>
        internal static string Routing_BoundingBox_TooSmall {
            get {
                return ResourceManager.GetString("Routing_BoundingBox_TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a finite number..
        /// </summary>
        internal static string Routing_Common_NonFiniteNumber {
            get {
                return ResourceManager.GetString("Routing_Common_NonFiniteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        internal static string Routing_Common_NullValue {
            get {
                return ResourceManager.GetString("Routing_Common_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxDetourRatio must be &gt;= 1.0. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_Constraints_InvalidDetourRatio {
            get {
                return ResourceManager.GetString("Routing_Constraints_InvalidDetourRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance cannot be negative. Got &apos;{0}&apos; meters..
        /// </summary>
        internal static string Routing_Distance_Negative {
            get {
                return ResourceManager.GetString("Routing_Distance_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be negative. Got &apos;{0}&apos; seconds..
        /// </summary>
        internal static string Routing_Duration_Negative {
            get {
                return ResourceManager.GetString("Routing_Duration_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation gain cannot be negative. Got &apos;{0}&apos; meters..
        /// </summary>
        internal static string Routing_ElevationGain_Negative {
            get {
                return ResourceManager.GetString("Routing_ElevationGain_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun Score must be within [0, 1]. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_FunScore_OutOfRange {
            get {
                return ResourceManager.GetString("Routing_FunScore_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be within [-90, 90]. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_Geo_InvalidLatitude {
            get {
                return ResourceManager.GetString("Routing_Geo_InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be within [-180, 180]. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_Geo_InvalidLongitude {
            get {
                return ResourceManager.GetString("Routing_Geo_InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphVersionId contains invalid characters. Allowed: letters, digits, &apos;-&apos;, &apos;_&apos;, &apos;.&apos;, &apos;:&apos;..
        /// </summary>
        internal static string Routing_GraphVersionId_InvalidChars {
            get {
                return ResourceManager.GetString("Routing_GraphVersionId_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphVersionId is required..
        /// </summary>
        internal static string Routing_GraphVersionId_Required {
            get {
                return ResourceManager.GetString("Routing_GraphVersionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphVersionId exceeds max length of {0}..
        /// </summary>
        internal static string Routing_GraphVersionId_TooLong {
            get {
                return ResourceManager.GetString("Routing_GraphVersionId_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline must contain at least 2 points. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_Polyline_TooFewPoints {
            get {
                return ResourceManager.GetString("Routing_Polyline_TooFewPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route geometry must be provided..
        /// </summary>
        internal static string Routing_Route_GeometryRequired {
            get {
                return ResourceManager.GetString("Routing_Route_GeometryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphVersionId must be provided..
        /// </summary>
        internal static string Routing_Route_GraphVersionRequired {
            get {
                return ResourceManager.GetString("Routing_Route_GraphVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route segments are invalid or empty..
        /// </summary>
        internal static string Routing_Route_SegmentsInvalid {
            get {
                return ResourceManager.GetString("Routing_Route_SegmentsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutePlan cannot define both End coordinate and a LoopSpec..
        /// </summary>
        internal static string Routing_RoutePlan_EndAndLoopNotAllowed {
            get {
                return ResourceManager.GetString("Routing_RoutePlan_EndAndLoopNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutePlan must define either an End coordinate or a LoopSpec..
        /// </summary>
        internal static string Routing_RoutePlan_EndOrLoopRequired {
            get {
                return ResourceManager.GetString("Routing_RoutePlan_EndOrLoopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints count exceeds allowed maximum. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_RoutePlan_WaypointsTooMany {
            get {
                return ResourceManager.GetString("Routing_RoutePlan_WaypointsTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteSegment geometry must be provided..
        /// </summary>
        internal static string Routing_RouteSegment_GeometryRequired {
            get {
                return ResourceManager.GetString("Routing_RouteSegment_GeometryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun Factor must be within [0, 10]. Got &apos;{0}&apos;..
        /// </summary>
        internal static string Routing_ScoringProfile_InvalidFunFactor {
            get {
                return ResourceManager.GetString("Routing_ScoringProfile_InvalidFunFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one scoring weight must be greater than 0..
        /// </summary>
        internal static string Routing_ScoringWeights_AllZero {
            get {
                return ResourceManager.GetString("Routing_ScoringWeights_AllZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be within [0, 1]. Got &apos;{1}&apos;..
        /// </summary>
        internal static string Routing_ScoringWeights_OutOfRange {
            get {
                return ResourceManager.GetString("Routing_ScoringWeights_OutOfRange", resourceCulture);
            }
        }
    }
}
