<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Curvia.Domain\Curvia.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pivot.Framework.Application" Version="1.0.2" />
    <PackageReference Include="Pivot.Framework.Infrastructure.Caching" Version="1.0.2" />
    <PackageReference Include="Pivot.Framework.Tools.DependencyInjection" Version="1.0.2" />
  </ItemGroup>

</Project>
